#!/usr/bin/env bash
set -Eeuo pipefail

PROFILE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd -- "$PROFILE_DIR/../.." && pwd)

# shellcheck source=../../configs/common.conf
source "$PROJECT_ROOT/configs/common.conf"
# shellcheck source=../../configs/mars.conf
source "$PROJECT_ROOT/configs/mars.conf"
# shellcheck source=layout.conf
source "$PROFILE_DIR/layout.conf"
