BOARD_ID=mars
BOARD_NAME='Milk-V Mars 8GB'
BOARD_VENDOR=milkv
KERNEL_SOURCE=starfive_linux_6_12
KERNEL_DEFCONFIG=starfive_visionfive2_defconfig
UBOOT_SOURCE=uboot_upstream
OPENSBI_SOURCE=starfive_opensbi
KERNEL_DTB=jh7110-milkv-mars.dtb
KERNEL_DTB_COMPATIBLE='milkv,mars'
UBOOT_DEFCONFIG=starfive_visionfive2_defconfig
UBOOT_VARIANT=mars
BOOTLOADER_MEDIA=spi-nor
ROOT_DEVICE_POLICY=uuid
NVME_POLICY=skip
EMMC_POLICY=capable
MARS_DTB_ALLOWED=1
