BOARD_ID=visionfive2
BOARD_NAME='StarFive VisionFive 2 8GB'
BOARD_VENDOR=starfive
KERNEL_SOURCE=starfive_linux_6_12
KERNEL_DEFCONFIG=starfive_visionfive2_defconfig
UBOOT_SOURCE=starfive_uboot
OPENSBI_SOURCE=starfive_opensbi
KERNEL_DTB=jh7110-starfive-visionfive-2-v1.3b.dtb
KERNEL_DTB_COMPATIBLE='starfive,visionfive-2-v1.3b'
UBOOT_DEFCONFIG=starfive_visionfive2_defconfig
UBOOT_VARIANT=visionfive2
BOOTLOADER_MEDIA=spi-nor
ROOT_DEVICE_POLICY=uuid
NVME_POLICY=required
EMMC_POLICY=capable
MARS_DTB_ALLOWED=0
